### ISSUE TITLE
save file on macos

### ISSUE THREAD

**Issue by PrzemyslawPluszowy** [UnluckyY1/flutter_downloads_folder#2]
hello can i select where file will be stored on macos?

**Comment by UnluckyY1** [comment]
Hey There 👋,
No, you can't. The whole purpose of the plugin is to save/copy files into the download folder.

**Comment by UnluckyY1** [comment]
Hey there 👋,

Yes, you can. While the main purpose of the plugin is to save/copy files into the download folder, there's an extension on the File class that allows you to copy your file to any location you want. Keep in mind that depending on the path you choose, you may need to request extra permissions to be able to write to the path you provided.


`await File("filePath").copyTo(folder.path, fileName,
        desiredExtension: desiredExtension);`
