### ISSUE TITLE
How to use with `image_picker` / `file_picker`?

### ISSUE THREAD

**Issue by lukehutch** [UnluckyY1/flutter_downloads_folder#6]
I want to enable my Flutter app to pick photos that have been downloaded by Safari on iOS. However, I can't see how to integrate `flutter_downloads_folder` with `file_picker` or `image_picker`. Is there a way to allow a Flutter app to pick a file from the downloads folder?

**Comment by UnluckyY1** [comment]
Check the example app, it already uses file_picker to pick the file and then copy it into your appfolder... 

https://github.com/UnluckyY1/flutter_downloads_folder/assets/48437666/6c418d6a-bec0-43ed-b2c1-5c81375f7bbe

**Comment by lukehutch** [comment]
Merci, I didn't see that...
