### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Jakuzeisme** [UnluckyY1/flutter_downloads_folder#8]
Yo, thanks a lot for this package.  I'm curious  about the reliability of this package. Cos I want to use it on production.
This is my situation here:
https://stackoverflow.com/questions/76999561/how-to-save-file-to-downloads-folder-on-android-33

**Comment by Jakuzeisme** [comment]
Sir?

**Comment by UnluckyY1** [comment]
It’s safe to use. I’m already using it in one of my apps in production. A year ago, I faced the same issue as you, and this package solved it perfectly. It will address the exact issue you’re encountering.

To clarify, for Android devices with API levels lower than 29, the plugin uses pure Dart code to copy the file to the Download folder and requests write permissions if necessary. For API 29 and higher, the plugin leverages native code with MediaStore to save the file, fully adhering to scoped storage requirements.

https://developer.android.com/training/data-storage/shared/media
